In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array 다차원 배열)

## 자료를 다차원 배열로 변환

In [2]:
# np.array() : 다차원 배열을 만드는 함수
lst = [1, 2, 3, 4]
lst_arr = np.array(lst)

In [3]:
lst_arr

array([1, 2, 3, 4])

In [4]:
type(lst_arr)

numpy.ndarray

In [5]:
# 튜플을 다차원배열로 변환
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [6]:
tu_arr

array([1, 2, 3, 4])

In [7]:
# 배열은 mutable의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = lst_arr
print(id(co_arr), id(lst_arr))

2397253270288 2397253270288


In [9]:
co_arr[0] = 100

In [10]:
co_arr

array([100,   2,   3,   4])

In [11]:
lst_arr

array([100,   2,   3,   4])

In [12]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열이 만들어지기 때문에 서로 다른 데이터가 됨
new_arr = np.array(lst_arr)

In [13]:
print(id(new_arr), id(lst_arr))

2397253269808 2397253270288


In [15]:
new_arr[0] = 99

In [16]:
new_arr

array([99,  2,  3,  4])

In [17]:
lst_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

### 자료형 지정해서 다차원 배열 만들기

In [19]:
fl_arr = np.array(lst, dtype = float)
fl_arr

array([1., 2., 3., 4.])

In [20]:
fl_arr.dtype

dtype('float64')

# 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [27]:
# 축의 개수
arr2d.ndim

2

In [28]:
arr2d.dtype

dtype('int64')

In [29]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [30]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

# 다차원 배열에서 원소 조회하기

## 1차원 배열에서 원소 조회하기

In [31]:
lst_arr

array([100,   2,   3,   4])

In [32]:
lst

[1, 2, 3, 4]

In [33]:
lst[0]

1

In [34]:
lst_arr[0]

np.int64(100)

## 다차원배열에서 원소 조회하기

In [35]:
# 배열을 리스트로 변환
lst2d = arr2d.tolist()

In [36]:
lst2d

[[1, 2, 3], [4, 5, 6]]

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# 리스트는 정수만 사용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱싱을 두 번 사용해야함
lst2d[0][1]

2

In [41]:
lst2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [42]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

np.int64(2)

In [44]:
arr2d[0][1]

np.int64(2)

## 슬라이싱

In [45]:
arr1 = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7]])
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [47]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [48]:
# 두 번째 행의 두 번째 열부터 끝 열까지
arr1[1, 1:]

array([5, 6, 7])

In [49]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

연습문제
- 아래의 행렬에서 값 7 을 인덱싱한다.

- 아래의 행렬에서 값 14 를 인덱싱한다.

- 아래의 행렬에서 배열 [6, 7] 을 슬라이싱한다.

- 아래의 행렬에서 배열 [7, 12] 를 슬라이싱한다.

- 아래의 행렬에서 배열 [[3, 4], [8, 9]] 를 슬라이싱한다.

In [50]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [51]:
# 값 7 을 인덱싱
m[1, 2]

np.int64(7)

In [52]:
# 값 14 를 인덱싱
m[-1, -1]

np.int64(14)

In [53]:
# 배열 [6, 7] 을 슬라이싱
m[1, 1:3]

array([6, 7])

In [58]:
# 배열 [7, 12] 를 슬라이싱
m[1:, 2]

array([ 7, 12])

In [56]:
m[1:, 2:3]

array([[ 7],
       [12]])

In [55]:
# 배열 [[3, 4], [8, 9]] 를 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

# 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능

- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 곱셈으로 리스트 요소를 반복하는 것은 가능
 
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 다차원배열 연산

## 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [59]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr.shape

(2, 3)

In [63]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
arr.T.shape

(3, 2)

## 배열 크기 변형

In [65]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
arr2 = arr1.reshape(3, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape의 형태 원소 중 하나는 -1로 대체할 수 있음

In [70]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
arr1.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [74]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [75]:
arr1.reshape(7, -1)

ValueError: cannot reshape array of size 12 into shape (7,newaxis)

In [76]:
arr1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

## 넘파이 함수의 특징

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함

- 유니버설 함수(universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [78]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [80]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

numpy._ArrayFunctionDispatcher

In [81]:
lst2d

[[1, 2, 3], [4, 5, 6]]

In [82]:
lst2d + lst2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [83]:
np.add(lst2d, lst2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

- 벡터화 연산이 필요한 이유
    - data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [84]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- 리스트를 통한 풀이

In [85]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [86]:
ans = []

for i in data:
    ans.append(i * 2)

ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [88]:
list(map(lambda x: x * 2, data))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

- 넘파이를 통한 풀이

In [89]:
data = np.array(data)

In [90]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [91]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [92]:
2 * a + b

array([12, 24, 36])

In [93]:
a == 2

array([False,  True, False])

In [94]:
[1, 2, 3] == 2

False

In [95]:
b > 10

array([False,  True,  True])

In [96]:
(a == 2) & (b > 10)

array([False,  True, False])

In [97]:
a[a == 2]

array([2])

In [101]:
a[[False, False, True]]

array([3])

- 배열끼리의 연산

In [102]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [103]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [104]:
arr1 * arr2

array([ 60,  77,  96, 117])

In [105]:
# arr1에 차원 추가
new_arr1 = arr1.reshape(4, 1)
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [106]:
new_arr1.shape

(4, 1)

In [107]:
# arr2에 차원 추가
new_arr2 = arr2.reshape(1, 4)
new_arr2

array([[10, 11, 12, 13]])

In [108]:
new_arr2.shape

(1, 4)

In [109]:
# 2차원 곱하기 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함

- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤

In [110]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [111]:
new_arr2

array([[10, 11, 12, 13]])

In [112]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

In [113]:
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [114]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [115]:
a

array([[1, 2],
       [3, 4]])

In [116]:
b

array([[5, 6],
       [7, 8]])

In [118]:
# * 연산자는 요소별 곱셈을 수행
a * b

array([[ 5, 12],
       [21, 32]])

In [119]:
# @ 연산자는 행렬 곱셈을 수행
a @ b

array([[19, 22],
       [43, 50]])

연습문제

- 아래의 배열에서 3의 배수를 찾아라.

- 아래의 배열에서 4로 나누면 1이 남는 수를 찾아라.

- 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [120]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [123]:
# 3의 배수 찾기
x[x % 3 == 0 ]

array([ 3,  6,  9, 12, 15, 18])

In [126]:
# 4로 나누면 1이 남는 수 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [130]:
# 3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요

### 1차원 배열

In [131]:
arr1 = np.array([1, 2, 3, 4])
arr1

array([1, 2, 3, 4])

In [132]:
# 합계
np.sum(arr1)

np.int64(10)

In [133]:
arr1.sum()

np.int64(10)

In [134]:
# 최댓값
arr1.max()

np.int64(4)

In [135]:
np.max(arr1)

np.int64(4)

In [136]:
# 최솟값
arr1.min()

np.int64(1)

In [137]:
# 최솟값의 위치
arr1.argmin()

np.int64(0)

In [138]:
np.argmin(arr1)

np.int64(0)

In [140]:
# 최댓값의 위치
np.argmax(arr1)

np.int64(3)

In [141]:
# 평균
arr1.mean()

np.float64(2.5)

In [143]:
# 중앙값
np.median(arr1)

np.float64(2.5)

### 2차원 배열

In [144]:
arr2 = arr1.reshape(2, 2)
arr2

array([[1, 2],
       [3, 4]])

In [145]:
# 모든 원소를 더한 합
np.sum(arr2)

np.int64(10)

In [146]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [147]:
arr2.sum(axis = 0)

array([4, 6])

In [148]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [149]:
arr2.sum(axis = 1)

array([3, 7])

In [152]:
arr3 = np.random.randint(0, 4, size = (2, 3))

In [153]:
arr3

array([[1, 0, 1],
       [3, 1, 3]], dtype=int32)

In [154]:
arr3.shape

(2, 3)

In [155]:
arr3.sum(axis = 0)

array([4, 1, 4])

In [156]:
arr3.sum(axis = 1)

array([2, 7])

### 3차원 배열

In [157]:
arr4 = np.arange(1, 9)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [158]:
arr5 = arr4.reshape(2, 2, 2)
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [159]:
# 모든 원소를 더한 합
np.sum(arr5)

np.int64(36)

In [160]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr5, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [161]:
# 각 2차원 배열의 0번축(열)의 합
np.sum(arr5, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [162]:
# 각 2차원 배열의 1번축(행)의 합
np.sum(arr5, axis = 2)

array([[ 3,  7],
       [11, 15]])

In [164]:
# 모든 2차원 배열의 열의 합
np.sum(arr5, axis = (0, 1))

array([16, 20])

In [166]:
# 모든 2차원 배열의 행의 합
np.sum(arr5, axis = (0, 2))

array([14, 22])

In [168]:
# 각 2차원 배열의 합
np.sum(arr5, axis = (1, 2))

array([10, 26])

In [169]:
arr6 = np.random.randint(0, 4, size = (2, 3, 4))
arr6

array([[[1, 2, 0, 1],
        [3, 0, 1, 1],
        [3, 0, 0, 2]],

       [[3, 1, 0, 0],
        [0, 2, 3, 1],
        [2, 0, 1, 3]]], dtype=int32)

In [170]:
arr6.sum(axis = 0)

array([[4, 3, 0, 1],
       [3, 2, 4, 2],
       [5, 0, 1, 5]])

In [171]:
arr6.sum(axis = 1)

array([[7, 2, 1, 4],
       [5, 3, 4, 4]])

In [172]:
arr6.sum(axis = 2)

array([[4, 5, 5],
       [4, 6, 6]])

In [173]:
arr6.sum(axis = (0, 1))

array([12,  5,  5,  8])

In [174]:
arr6.sum(axis = (0, 2))

array([ 8, 11, 11])

In [175]:
arr6.sum(axis = (1, 2))

array([14, 16])

연습문제

실수로 이루어진 5x6 형태의 데이터 행렬을 만들고 다음의 값을 구한다

- 전체의 최댓값

- 각 행의 합

- 각 행의 최댓값

- 각 열의 평균

- 각 열의 최솟값

In [176]:
x = np.random.random((5, 6))
x

array([[0.62972712, 0.61219091, 0.26876251, 0.28951135, 0.19350585,
        0.08075685],
       [0.34724814, 0.35752887, 0.93220337, 0.81855032, 0.35292262,
        0.66305681],
       [0.05558115, 0.49728475, 0.37167228, 0.17898964, 0.4295792 ,
        0.95460064],
       [0.9049708 , 0.30944907, 0.97014544, 0.93460113, 0.69114764,
        0.64851249],
       [0.85827741, 0.58185129, 0.93622446, 0.88832064, 0.32672881,
        0.9712693 ]])

In [177]:
# 전체의 최댓값
x.max()

np.float64(0.9712692972513575)

In [178]:
# 각 행의 합
x.shape

(5, 6)

In [179]:
x.sum(axis = 1)

array([2.07445458, 3.47151012, 2.48770766, 4.45882657, 4.5626719 ])

In [180]:
# 각 행의 최댓값
x.max(axis = 1)

array([0.62972712, 0.93220337, 0.95460064, 0.97014544, 0.9712693 ])

In [181]:
# 각 열의 평균
x.mean(axis = 0)

array([0.55916092, 0.47166098, 0.69580161, 0.62199461, 0.39877682,
       0.66363922])

In [182]:
# 각 열의 최솟값
x.min(axis = 0)

array([0.05558115, 0.30944907, 0.26876251, 0.17898964, 0.19350585,
       0.08075685])

# Inf와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음

In [183]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\Administrator\AppData\Local\Temp\ipykernel_4848\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\Administrator\AppData\Local\Temp\ipykernel_4848\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

# 연습문제

- 아래의 행렬에서 배열 [8, 14] 를 슬라이싱한다.

- 아래의 행렬에서 배열 [[11, 12], [17, 18]] 을 슬라이싱한다.

- 아래의 행렬에서 배열 [3, 9, 15, 21] 을 슬라이싱한다.

In [2]:
m = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [22, 23, 24]]])

In [4]:
# 배열 [8, 14] 를 슬라이싱
m.shape

(4, 2, 3)

In [13]:
m[1:3, 0, 1]

array([ 8, 14])

In [22]:
# 배열 [[11, 12], [17, 18]]
m[1:3, 1, 1:]

array([[11, 12],
       [17, 18]])

In [24]:
# 배열 [3, 9, 15, 21] 을 슬라이싱
m[:, 0, 2]

array([ 3,  9, 15, 21])

- 각 2차원 배열에서의 최댓값
- 각 2차원 배열에서의 행의 합
- 각 2차원 배열에서의 각 행의 최댓값
- 전체 열의 평균
- 각 2차원 배열에서의 열의 평균
- 각 2차원 배열에서의 각 열의 최솟값

In [25]:
data_3d = np.random.random((3, 5, 6))
data_3d

array([[[0.89639707, 0.97279189, 0.90209977, 0.04460788, 0.4742066 ,
         0.32186162],
        [0.9679947 , 0.83265391, 0.15322301, 0.98975224, 0.79399088,
         0.81299821],
        [0.73784391, 0.3999017 , 0.46065726, 0.24142881, 0.0664527 ,
         0.25344431],
        [0.70140137, 0.19728165, 0.50801355, 0.68950894, 0.34678075,
         0.17490175],
        [0.22242412, 0.7458081 , 0.52631361, 0.54657241, 0.21633986,
         0.51270451]],

       [[0.80763825, 0.1679132 , 0.4868321 , 0.21076521, 0.14695734,
         0.64409512],
        [0.87632967, 0.52266524, 0.48495693, 0.84902774, 0.89203953,
         0.3888102 ],
        [0.58340849, 0.70671099, 0.9588115 , 0.65770406, 0.88898557,
         0.13406174],
        [0.60092752, 0.95498623, 0.29135914, 0.06419331, 0.75533715,
         0.12722849],
        [0.35021346, 0.36131576, 0.70503746, 0.92523481, 0.61692159,
         0.98481071]],

       [[0.12880161, 0.74458538, 0.46708016, 0.00441215, 0.11712518,
         0.846559

In [26]:
# 각 2차원 배열에서의 최댓값
data_3d.max(axis = (1, 2))

array([0.98975224, 0.98481071, 0.99735295])

In [27]:
# 각 2차원 배열에서의 행의 합
data_3d.sum(axis = 2)

array([[3.61196483, 4.55061295, 2.15972868, 2.617888  , 2.7701626 ],
       [2.46420122, 4.01382931, 3.92968235, 2.79403183, 3.94353378],
       [2.30856381, 2.66981853, 3.45517063, 3.92169728, 4.12258493]])

In [28]:
# 각 2차원 배열에서의 각 행의 최댓값
data_3d.max(axis = 2)

array([[0.97279189, 0.98975224, 0.73784391, 0.70140137, 0.7458081 ],
       [0.80763825, 0.89203953, 0.9588115 , 0.95498623, 0.98481071],
       [0.84655933, 0.67899723, 0.85226928, 0.99735295, 0.95970828]])

In [29]:
# 전체 열의 평균
data_3d.mean(axis = (0, 1))

array([0.58780691, 0.61163756, 0.55696838, 0.55299922, 0.45186427,
       0.52762171])

In [30]:
# 각 2차원 배열에서의 열의 평균
data_3d.mean(axis = 1)

array([[0.70521223, 0.62968745, 0.51006144, 0.50237406, 0.37955416,
        0.41518208],
       [0.64370348, 0.54271828, 0.58539943, 0.54138502, 0.66004824,
        0.45580125],
       [0.41450502, 0.66250696, 0.57544426, 0.61523858, 0.31599042,
        0.7118818 ]])

In [31]:
# 각 2차원 배열에서의 각 열의 최솟값
data_3d.min(axis = 1)

array([[0.22242412, 0.19728165, 0.15322301, 0.04460788, 0.0664527 ,
        0.17490175],
       [0.35021346, 0.1679132 , 0.29135914, 0.06419331, 0.14695734,
        0.12722849],
       [0.12880161, 0.3375388 , 0.26784599, 0.00441215, 0.11712518,
        0.29963001]])