In [1]:
import numpy as np

# 스칼라와 벡터

- 벡터와 행렬은 특정 텐서(tensor)를 부르는 이름

- 텐서의 이름을 부여하는 원칙은 차원인 축(axis)을 기준으로 지정
    - 0차원(축이 없는 경우) : 스칼라(scalar)
    - 1차원(축이 하나) : 벡터(vector)
    - 2차원 : 행렬(matrix)
    - 3차원 : 큐브(cube) 또는 3차원 텐서
    - 더 차원이 높을 경우는 차원을 기준으로 n차원 텐서 라고 부름

## 스칼라

- 0차원 배열
- 크기를 표현
- 가장 기본적인 값
- 수학에서 배운 정수나 실수는 하나의 물리량인 크기를 표현하는데, 이 값을 스칼라 라고 함

In [2]:
scalar_arr = np.array(43)

In [4]:
# array에서 스칼라는 대괄호 없이 숫자만 표시
# 대괄호는 벡터(1차원 배열)부터 사용
scalar_arr

array(43)

In [5]:
type(scalar_arr)

numpy.ndarray

In [6]:
# 스칼라는 0차원
scalar_arr.ndim

0

In [8]:
# 축이 없기 때문에 빈 튜플
scalar_arr.shape

()

In [10]:
# array로 스칼라를 만들어도 dtype을 가짐
scalar_arr.dtype

dtype('int64')

## 벡터

- 1차원 배열

In [11]:
vector = np.array([43])

In [12]:
vector

array([43])

In [13]:
type(vector)

numpy.ndarray

In [15]:
# 1차원 배열
vector.ndim

1

In [16]:
vector.shape

(1,)

## 배열 생성 함수

### zeros

- 크기가 정해져 있고 모든 값이 0인 배열 생성
- 인수로는 배열의 크기를 전달

In [17]:
# 1차원 배열
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [18]:
# 2차원 배열
zero_arr2 = np.zeros((2, 3))
zero_arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

- dtype 인수를 명시하면 해당 자료형 원소 배열을 생성

In [19]:
zero_arr3 = np.zeros((5, 2), dtype = int)
zero_arr3

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### ones

- 모든 값이 1인 배열 생성

In [20]:
one_arr = np.ones((2, 3, 4), dtype = int)
one_arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### zeros_like, ones_like

- 다른 배열과 같은 크기의 배열을 생성

In [21]:
zero_arr4 = np.zeros_like(one_arr)
zero_arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [22]:
one_arr2 = np.ones_like(zero_arr3)
one_arr2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [23]:
one_arr3 = np.ones_like(zero_arr2)
one_arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

### arange

- 파이썬의 range와 유사한 함수

- range와 같이 시작점, 종료점, 증감값을 인자로 전달
    - 종료점은 필수

In [24]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
vector.dtype

dtype('int64')

- 인자로 실수를 지정할 수 있음

In [28]:
vector1 = np.arange(10.5, 20.5, 0.5)
vector1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [29]:
vector1.dtype

dtype('float64')

In [30]:
# 1차원 배열을 생성하면서 바로 2차원 배열로 형상 변경
vector2 = np.arange(60).reshape(6, 10)
vector2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [31]:
vector2.shape

(6, 10)

In [32]:
vector3 = np.arange(60).reshape(3, 4, 5)
vector3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

### linspace

- arange와의 차이점
    - 종료점도 포함해서 원소를 생성
    - 세 번째 인자로 간격 대신 원소의 개수를 전달
        - 초기값은 50
     
    - 기본으로 실수를 가진 원소를 만듦

In [33]:
lin = np.linspace(1, 10, 10)
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
lin.dtype

dtype('float64')

In [35]:
# 값의 간격을 표시하는 증분(incremental)을 확인할 수 있음
lin2 = np.linspace(1, 2, 10, retstep = True)
lin2

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 np.float64(0.1111111111111111))

In [36]:
# 종료값을 제외할 수도 있음
lin3 = np.linspace(1, 10, 10, endpoint = False, retstep = True)
lin3

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), np.float64(0.9))

## 벡터의 크기 및 단위 벡터 구하기

- 선형대수의 벡터는 크기와 방향을 가짐

- 벡터의 크기는 노름(norm)이라고 부름

- 벡터는 평면 좌표의 점을 표시하듯이 2개의 원소를 가진 것을 대표적으로 사용
    - 벡터의 크기는 피타고라스의 정리를 사용

### 벡터의 크기 계산

In [37]:
# 두 개의 원소를 가지는 1차원 배열 생성
v = np.arange(3, 5)
v

array([3, 4])

In [38]:
# 벡터의 크기를 구하기 위해 각 원소를 제곱하여 합산한 후 제곱근 계산
v_p = np.power(v, 2)
v_p

array([ 9, 16])

In [40]:
np.sqrt(np.sum(v_p))

np.float64(5.0)