In [59]:
import numpy as np
from scipy.stats import chi2_contingency

7. 아래의 지시사항에 따라 각각 적절한 다차원 배열을 생성하시오

가.  0부터 9까지의 숫자가 순서대로 하나씩 들어있는 1차원 배열을 생성하는 코드를 작성하시오

나. 모든 요소가 True 로 채워진 (3, 3) 의 형상을 가지는 다차원 배열을 생성하는 코드를 작성하시오

다. 바깥쪽 테두리에는 1이 채워져 있고 내부는 0으로 채워진 (10, 10) 형상의 2차원 배열을 생성하는 코드를 작성하시오

라. (8, 8) 형상의 2차원 배열을 0과 1을 번갈아가며 채워 생성하는 코드를 작성하시오

In [2]:
# 7-가. 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 7-나
np.ones((3, 3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
# 7-다
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
# 7-라
arr = np.zeros((8, 8), dtype = int)
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

8. 아래의 지시사항에 따라 각각 적절한 다차원 배열을 출력하시오

가. arr = np.arange(10) 이라고 할 때 arr 에서 홀수들만 추출하여 출력하시오


나. arr = np.arange(10) 에서 홀수들을 -1로 수정하여 출력하시오
예) [0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


다. 배열 a와 b가 아래와 같을 때, a와 b의 요소 중 동일한 인덱스에 동일한 값이 들어있는 요소들만 추출하여 출력하시오

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

예) array([2, 2, 4, 4])
 

라. a = np.array([2, 6, 1, 9, 10, 3, 27]) 라고 할 때 5이상 10이하인 값만 추출하여 출력하시오


마. arr = np.arange(9).reshape(3,3) 라고 할 때 arr의 첫 번째 컬럼과 두 번째 컬럼의 순서를 바꾸어 출력하시오

예) array([[1, 0, 2],       [4, 3, 5],       [7, 6, 8]])
 

바. arr = np.arange(9).reshape(3,3) 라고 할 때 행의 순서를 반대로 바꾸어 출력하시오

예) array([[6, 7, 8],       [3, 4, 5],       [0, 1, 2]])

In [12]:
# 가. arr = np.arange(10) 이라고 할 때 arr 에서 홀수들만 추출하여 출력하시오
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [14]:
# 나. arr = np.arange(10) 에서 홀수들을 -1로 수정하여 출력하시오 예) [0, -1, 2, -1, 4, -1, 6, -1, 8, -1]
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
# 다. 배열 a와 b가 아래와 같을 때, a와 b의 요소 중 동일한 인덱스에 동일한 값이 들어있는 요소들만 추출하여 출력하시오
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

a[a == b]

array([2, 2, 4, 4])

In [19]:
# 라. a = np.array([2, 6, 1, 9, 10, 3, 27]) 라고 할 때 5이상 10이하인 값만 추출하여 출력하시오
a = np.array([2, 6, 1, 9, 10, 3, 27])
a >= 5

array([False,  True, False,  True,  True, False,  True])

In [20]:
a <= 10

array([ True,  True,  True,  True,  True,  True, False])

In [22]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [28]:
# 마. arr = np.arange(9).reshape(3,3) 라고 할 때 arr의 첫 번째 컬럼과 두 번째 컬럼의 순서를 바꾸어 출력하시오
arr = np.arange(9).reshape(3,3)
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [30]:
# 바. arr = np.arange(9).reshape(3,3) 라고 할 때 행의 순서를 반대로 바꾸어 출력하시오
arr = np.arange(9).reshape(3,3)
arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [32]:
# 9. arr = np.arange(10) 이라고 할 때 arr을 2개의 행을 갖는 2차원 배열로 형상을 변경하는 코드를 작성하시오
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. 다차원배열 arr 가 아래와 같다고 할 때
- arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
- 아래의 지시사항에 따라 연산을 수행하는 코드를 각각 작성하시오
- 가. 각 2차원 배열의 각 행의 평균값을 계산하시오
- 나. 각 2차원 배열의 합을 계산하시오
- 다. 각 2차원 배열의 각 열의 표준편차를 계산하시오

In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

In [34]:
arr.shape

(3, 2, 3)

In [35]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [36]:
# 가. 각 2차원 배열의 각 행의 평균값을 계산하시오
np.mean(arr, axis = 2)

array([[ 2.,  5.],
       [ 8., 11.],
       [14., 17.]])

In [37]:
# 나. 각 2차원 배열의 합을 계산하시오
np.sum(arr, axis = (1, 2))

array([21, 57, 93])

In [38]:
# 다. 각 2차원 배열의 각 열의 표준편차를 계산하시오
np.std(arr, axis = 1)

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

11. 배열 arr이 아래와 같을 때, 아래의 지시사항에 따라 데이터 전처리를 수행하는 코드를 각각 작성하시오

- arr = np.arange(1, 9).reshape(4, 2)

- 가. 각 열의 값이 최솟값이 0, 최댓값이 1이 될 수 있도록 정규화를 하려고 한다

- 정규화의 공식은 ((각 요소 값 - 해당 열의 최솟값) / (해당 열의 최댓값 - 해당 열의 최솟값))

- 나. 각 행 내에서 해당 요소가 차지하는 비율로 값을 수정하려고 한다
- 정규화의 공식은 (각 요소 값 / 해당 행의 합)

In [39]:
arr = np.arange(1, 9).reshape(4, 2)

In [40]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
arr.min(axis = 0)

array([1, 2])

In [43]:
arr - arr.min(axis = 0)

array([[0, 0],
       [2, 2],
       [4, 4],
       [6, 6]])

In [44]:
((arr - arr.min(axis = 0)) / (arr.max(axis = 0) - arr.min(axis = 0)))

array([[0.        , 0.        ],
       [0.33333333, 0.33333333],
       [0.66666667, 0.66666667],
       [1.        , 1.        ]])

In [45]:
# 정규화의 공식은 (각 요소 값 / 해당 행의 합)
np.sum(arr, axis = 1)

array([ 3,  7, 11, 15])

In [46]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.sum(arr, axis = 1).reshape(-1, 1)

array([[ 3],
       [ 7],
       [11],
       [15]])

In [50]:
arr / np.sum(arr, axis = 1).reshape(-1, 1)

array([[0.33333333, 0.66666667],
       [0.42857143, 0.57142857],
       [0.45454545, 0.54545455],
       [0.46666667, 0.53333333]])

12.  아래의 지시사항에 따라 다차원배열을 적절하게 슬라이싱하는 코드를 작성하시오

- arr = np.arange(2 * 3 * 4).reshape((2, 3, 4))

- 가. arr에서 array([[14, 15], [18, 19], [22, 23]]) 를 슬라이싱

- 나. arr에서 array([[ 2,  6, 10], [14, 18, 22]]) 를 슬라이싱

- 다. array([[ 1,  5,  9], [13, 17, 21]]) 를 슬라이싱

In [51]:
arr = np.arange(2 * 3 * 4).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [54]:
# 가. arr에서 array([[14, 15], [18, 19], [22, 23]]) 를 슬라이싱
arr[1, :, 2:]

array([[14, 15],
       [18, 19],
       [22, 23]])

In [56]:
# 나. arr에서 array([[ 2, 6, 10], [14, 18, 22]]) 를 슬라이싱
arr[:, :, 2]

array([[ 2,  6, 10],
       [14, 18, 22]])

In [57]:
# 다. array([[ 1, 5, 9], [13, 17, 21]]) 를 슬라이싱
arr[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

13. 남성 700명과 여성 500명이 있다.

- 남성 중 기혼자의 비율은 30% 이고, 여성 중 기혼자의 비율은 20% 이다.

- 남성과 여성의 성별이 혼인 여부에 영향을 주는지 확인하려 한다.

- 적절한 통계검정을 진행하고 검증된 p_value 결과를 바탕으로 성별에 따른 혼인여부의 분포에 통계적으로 유의미한 차이가 있는지를 답안으로 작성하시오

- 단, 유의수준은 0.05를 기준으로 한다.

In [58]:
man = 700
woman = 500

# 기혼자 수
man_married = int(man * 0.3)
woman_married = int(woman * 0.2)

# 미혼자 수
man_single = man - man_married
woman_single = woman - woman_married

data = np.array([[man_married, man_single],
                 [woman_married, woman_single]])
data

array([[210, 490],
       [100, 400]])

In [60]:
chi2_contingency(data)

Chi2ContingencyResult(statistic=np.float64(14.70545228602495), pvalue=np.float64(0.00012568242320118222), dof=1, expected_freq=array([[180.83333333, 519.16666667],
       [129.16666667, 370.83333333]]))